### ISSUE TITLE
Добавить подсказку, что 05_objects начало проекта

### ISSUE THREAD

**Issue by johnnymill** [netology-code/kt-homeworks#11]
Я думаю стоит добавить подсказку, что на базе этого проекта будут следующие задания.
А именно информацию, что все решения в итоге будут храниться в одном репозитории.

Например, я на это не расчитывал и пошел по пути сдачи заданий по курсу Java, где каждое задание - новый проект. Здесь это привело к тому, что
 - начальный проект назван неправильно (отражает суть текущего задания 05_objects), что делает не актуальным при расширении
 - в следующем задании (06_inheritance) я начал с создания нового проекта, не предполагая заранее, что это неверно. Кстати, там вначале так и написано "Создайте на вашем компьютере Gradle-проект"

**Comment by amostyaev** [comment]
Здравствуйте, Иван!

6-е задание можно сдавать как Pull Request к 5-ому, но это не обязательно. Если удобнее создавать отдельный проект, то можно без проблем создавать отдельный, при проверке с этим не будет проблем.

Успехов!
