### ISSUE TITLE
Ошибка в конфиге workflow/gradle.yml 

### ISSUE THREAD

**Issue by chemax** [netology-code/kt-homeworks#2]
Выполняю https://github.com/netology-code/kt-homeworks/tree/master/04_functions#задача-2---ci

1. Создаю файл .github/workflow/gradle.yml по образцу из задачи в разделе Actions github'а
2. Делаю git pull локально
3. Делаю commit & push изменений локальных в репозиторий.
4. Ожидаю: workflow run, получаю ничего.
5. Ошибка в конфиге для workflow - по дефолту гитхаб создаёт ветку main, не master. В конфиге - master.

**Comment by Onotole1** [comment]
Код для gradle.yml обновлён для запуска на master и на main
https://github.com/netology-code/kt-homeworks/blob/master/04_functions/README.md
