### ISSUE TITLE
Rules in descriptions task 1.3.1

### ISSUE THREAD

**Issue by vOrzee** [netology-code/kt-homeworks#3]
> Если количество секунд от суток до двух, то - сегодня.
Если количество секунд от двух суток до трёх, то - вчера.
Если количество секунд больше трёх суток, то - давно.

Если прошло более суток не очень уместно слово `сегодня`, возможно стоит "сдвинуть" на уровень:
4. Если количество секунд от суток до двух, то - `вчера`.
5. Если количество секунд от двух суток до трёх, то - `позавчера`
6. Если количество секунд больше трёх суток, то - `давно`.

**Comment by amostyaev** [comment]
Спасибо! Исправлено.
